export declare type OperationType = 'order' | 'cancel';
export declare type OrderSide = 'bid' | 'ask';
export declare type OrderType = 'market' | 'limit';
export declare type OrderStatus = 'new' | 'partial' | 'filled' | 'liquidityStarved';
export declare type OrderState = 'open' | 'closed';
export declare type TTaker = {
    assetId: string;
    filledPrice: number;
    filledSize: number;
    filledValue: number;
    isClosed: boolean;
    isLiquidityStarved: boolean;
    isPartial: boolean;
    orderSide: OrderSide;
    orderSize: number;
    portfolioId: string;
    sizeRemaining: number;
    orderId: string;
    orderType?: OrderType;
    tags?: any;
};
export declare type TMaker = {
    orderId?: string;
    assetId: string;
    filledPrice: number;
    filledSize: number;
    filledValue: number;
    isClosed: boolean;
    isPartial: boolean;
    orderSide: OrderSide;
    orderSize: number;
    portfolioId: string;
    sizeRemaining: number;
};
export declare type TExchangeTrade = {
    tradeId: string;
    assetId: string;
    executedAt: string;
    taker: TTaker;
    makers: TMaker[];
    createdAt?: string;
};
