export declare type OrderSide = 'bid' | 'ask';
export declare type OrderType = 'market';
export declare type OrderStatus = 'new' | 'partial' | 'filled' | 'liquidityStarved';
export declare type OrderState = 'open' | 'closed';
export declare type TOrderConfig = {
    assetId: string;
    orderId: string;
    portfolioId: string;
    orderSide: OrderSide;
    orderSize: number;
    orderType?: OrderType;
    tags?: any;
    sizeRemaining?: number;
};
export declare type TOrder = {
    assetId: string;
    orderId: string;
    portfolioId: string;
    orderType: OrderType;
    orderSide: OrderSide;
    orderSize: number;
    tags?: any;
    sizeRemaining: number;
    orderStatus: OrderStatus;
    orderState: OrderState;
};
export declare type TTaker = {
    assetId: string;
    orderSide: OrderSide;
    orderSize: number;
    orderId: string;
    portfolioId: string;
    orderType?: OrderType;
    tags?: any;
    sizeRemaining: number;
    filledSize: number;
    filledValue: number;
    filledPrice: number;
    isPartial: boolean;
    isClosed: boolean;
    isLiquidityStarved: boolean;
};
export declare type TMaker = {
    assetId: string;
    orderSide: OrderSide;
    orderSize: number;
    portfolioId: string;
    sizeRemaining: number;
    filledSize: number;
    filledValue: number;
    filledPrice: number;
    isPartial: boolean;
    isClosed: boolean;
};
