import { OrderSide, OrderType } from '../..';
export declare type TNewPortfolioOrderProps = {
    assetId: string;
    orderSide: OrderSide;
    orderSize: number;
    orderType: OrderType;
    orderPrice?: number;
    tags?: any;
    xids?: any;
};
export declare type TPortfolioOrder = {
    orderId: string;
    assetId: string;
    orderType: OrderType;
    orderSide: OrderSide;
    orderSize: number;
    orderPrice?: number;
    sizeRemaining?: number;
    tags?: any;
    events: any[];
    orderStatus: string;
    orderState: string;
    createdAt: string;
    closedAt?: string;
    reason?: string;
    filledPrice?: number;
    filledSize?: number;
    filledValue?: number;
    executedAt?: string;
};
export declare type TPortfolioOrderPatch = {
    closedAt?: string;
    filledPrice?: number;
    filledSize?: number;
    filledValue?: number;
    sizeRemaining?: number;
    orderStatus?: string;
    orderState?: string;
    reason?: string;
    executedAt?: string;
};
